dist: trusty
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy3"
matrix:
  include:
  - python: 3.7
    dist: xenial
  - python: 3.8
    dist: xenial
  - python: pypy
    dist: xenial
  - python: pypy3
    dist: xenial
before_install:
  - pip install --upgrade pip setuptools
install:
  - pip install -r requirements.txt
  - pip install coveralls
script: coverage run --source=digitalriver setup.py test
after_success: coveralls
deploy:
  provider: pypi
  user: joamag
  password:
    secure: jGAcdvwfetq9W3EfgsxLU3qGO9EI/RghoS/w7UPm2qHx99mhNDseepHksSwXIJHNA8bABYtIR7O2XrLFb2kflrNIab3h9u3OAa8lLSPEVDsyoNZDUPexATV4X7nhLwgiYq1Cr17dDGxl7cW6wAqnz5wbScmk/atzfM0JBwu58G0=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: "2.7"
